### ISSUE TITLE
[Answer] I need to know if this works on Android 11

### ISSUE THREAD

**Issue by githubberguy** [SkyTubeTeam/SkyTubeLegacy#33]
i wanna use this on android 11.

**Comment by drogga** [comment]
@githubberguy
_Here's an `answer` to your `question` (referring to the wrong tag in the subject title)_: You better use https://github.com/SkyTubeTeam/SkyTube instead, but this one should work as well. You can now close this, _or @gzsombor can when he's around (very rarely it looks like, because there's no one else around that can merge my PRs there...)_.
